# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e11e73eae0d4e36d7fafe0da677542e83268224ba6d1ab34a1c9a04619666ec80422d5293c1b39b44d80a6892d82897450bf5aca9208ac5a604846175cbac1

test:
  secret_key_base: 01596f62c7d6e8604efbc2bff135181c75b47f2b6e467eaa36d48a07973dbc1f5ed3f40d82b25b28a2edc3960bf22f2c9fa53c283c45d419c93436081c4f2ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
